X:www.mircx.comURL:www.mircx.com
X:www.xcalibre.comURL:www.xcalibre.com
?:www.mirc.co.ukURL:www.mirc.co.uk
?:http://superdumb.cjb.netURL:http://superdumb.cjb.net
?:www.freeBSD.orgURL:www.freeBSD.org
?:http://sabahchat.cjb.netURL:http://sabahchat.cjb.net
?:www.MyHacK.VBHQ.comURL:www.MyHacK.VBHQ.com
?:http://www.rootshell.comURL:http://www.rootshell.com
?:www.northenstar.comURL:www.northenstar.com
?:http://darknet.serb.org/exploits.htmlURL:http://darknet.serb.org/exploits.html
?:http://www.bahamut.netURL:http://www.bahamut.net
?:http://www.mynuke.da.ruURL:http://www.mynuke.da.ru
?:http://www.macpower.org/dalmac/ircintro.htmlURL:http://www.macpower.org/dalmac/ircintro.html
?:http://www.antionline.com/URL:http://www.antionline.com/
?:http://Opserv.cjb.netURL:http://Opserv.cjb.net
?:http://hardsoft.da.ru/URL:http://hardsoft.da.ru/
?:http://www.attrition.orgURL:http://www.attrition.org
?:http://www.d3vilz.i-p.comURL:http://www.d3vilz.i-p.com
